# CI config for shell runner

stages:
  - build
  - release

build:
  stage: build
  script:
    - ./gradlew build

jar:
  stage: release
  script:
    - ./gradlew jar
  artifacts:
    paths:
      - build/libs/*-standalone.jar
