# CI config for shell runner

stages:
  - build
  - package
  - release

build:
  stage: build
  script:
    - ./gradlew build

jar:
  stage: package
  script:
    - ./gradlew jar
  artifacts:
    paths:
      - build/libs/*-standalone.jar

podman:
  stage: release
  needs:
    - jar
  script:
    - podman build -t pproj/tutti .
    - podman push pproj/tutti
  only:
    - main
